
package com.prime.jax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScreenSoap", targetNamespace = "http://www.acumatica.com/generic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScreenSoap {


    /**
     * 
     * @param scenario
     * @return
     *     returns com.prime.jax.ArrayOfCommand
     */
    @WebMethod(operationName = "GetScenario", action = "http://www.acumatica.com/generic/GetScenario")
    @WebResult(name = "GetScenarioResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "GetScenario", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.GetScenario")
    @ResponseWrapper(localName = "GetScenarioResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.GetScenarioResponse")
    public ArrayOfCommand getScenario(
        @WebParam(name = "scenario", targetNamespace = "http://www.acumatica.com/generic/")
        String scenario);

    /**
     * 
     * @param password
     * @param name
     * @return
     *     returns com.prime.jax.LoginResult
     */
    @WebMethod(operationName = "Login", action = "http://www.acumatica.com/generic/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.LoginResponse")
    public LoginResult login(
        @WebParam(name = "name", targetNamespace = "http://www.acumatica.com/generic/")
        String name,
        @WebParam(name = "password", targetNamespace = "http://www.acumatica.com/generic/")
        String password);

    /**
     * 
     */
    @WebMethod(operationName = "Logout", action = "http://www.acumatica.com/generic/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.LogoutResponse")
    public void logout();

    /**
     * 
     * @param date
     */
    @WebMethod(operationName = "SetBusinessDate", action = "http://www.acumatica.com/generic/SetBusinessDate")
    @RequestWrapper(localName = "SetBusinessDate", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetBusinessDate")
    @ResponseWrapper(localName = "SetBusinessDateResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetBusinessDateResponse")
    public void setBusinessDate(
        @WebParam(name = "date", targetNamespace = "http://www.acumatica.com/generic/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param localeName
     */
    @WebMethod(operationName = "SetLocaleName", action = "http://www.acumatica.com/generic/SetLocaleName")
    @RequestWrapper(localName = "SetLocaleName", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetLocaleName")
    @ResponseWrapper(localName = "SetLocaleNameResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetLocaleNameResponse")
    public void setLocaleName(
        @WebParam(name = "localeName", targetNamespace = "http://www.acumatica.com/generic/")
        String localeName);

    /**
     * 
     * @param mode
     */
    @WebMethod(operationName = "SetSchemaMode", action = "http://www.acumatica.com/generic/SetSchemaMode")
    @RequestWrapper(localName = "SetSchemaMode", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetSchemaMode")
    @ResponseWrapper(localName = "SetSchemaModeResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SetSchemaModeResponse")
    public void setSchemaMode(
        @WebParam(name = "mode", targetNamespace = "http://www.acumatica.com/generic/")
        SchemaMode mode);

    /**
     * 
     */
    @WebMethod(operationName = "SM201010Clear", action = "http://www.acumatica.com/generic/SM201010/Clear")
    @RequestWrapper(localName = "SM201010Clear", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010Clear")
    @ResponseWrapper(localName = "SM201010ClearResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010ClearResponse")
    public void sm201010Clear();

    /**
     * 
     * @return
     *     returns com.prime.jax.ProcessResult
     */
    @WebMethod(operationName = "SM201010GetProcessStatus", action = "http://www.acumatica.com/generic/SM201010/GetProcessStatus")
    @WebResult(name = "GetProcessStatusResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM201010GetProcessStatus", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010GetProcessStatus")
    @ResponseWrapper(localName = "SM201010GetProcessStatusResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010GetProcessStatusResponse")
    public ProcessResult sm201010GetProcessStatus();

    /**
     * 
     * @return
     *     returns com.prime.jax.SM201010Content
     */
    @WebMethod(operationName = "SM201010GetSchema", action = "http://www.acumatica.com/generic/SM201010/GetSchema")
    @WebResult(name = "GetSchemaResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM201010GetSchema", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010GetSchema")
    @ResponseWrapper(localName = "SM201010GetSchemaResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010GetSchemaResponse")
    public SM201010Content sm201010GetSchema();

    /**
     * 
     * @param schema
     */
    @WebMethod(operationName = "SM201010SetSchema", action = "http://www.acumatica.com/generic/SM201010/SetSchema")
    @RequestWrapper(localName = "SM201010SetSchema", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010SetSchema")
    @ResponseWrapper(localName = "SM201010SetSchemaResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010SetSchemaResponse")
    public void sm201010SetSchema(
        @WebParam(name = "schema", targetNamespace = "http://www.acumatica.com/generic/")
        SM201010Content schema);

    /**
     * 
     * @param topCount
     * @param filters
     * @param includeHeaders
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.ArrayOfArrayOfString
     */
    @WebMethod(operationName = "SM201010Export", action = "http://www.acumatica.com/generic/SM201010/Export")
    @WebResult(name = "ExportResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM201010Export", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010Export")
    @ResponseWrapper(localName = "SM201010ExportResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010ExportResponse")
    public ArrayOfArrayOfString sm201010Export(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfFilter filters,
        @WebParam(name = "topCount", targetNamespace = "http://www.acumatica.com/generic/")
        int topCount,
        @WebParam(name = "includeHeaders", targetNamespace = "http://www.acumatica.com/generic/")
        boolean includeHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnError);

    /**
     * 
     * @param data
     * @param breakOnIncorrectTarget
     * @param includedHeaders
     * @param filters
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.SM201010ArrayOfImportResult
     */
    @WebMethod(operationName = "SM201010Import", action = "http://www.acumatica.com/generic/SM201010/Import")
    @WebResult(name = "ImportResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM201010Import", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010Import")
    @ResponseWrapper(localName = "SM201010ImportResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010ImportResponse")
    public SM201010ArrayOfImportResult sm201010Import(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfFilter filters,
        @WebParam(name = "data", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfArrayOfString data,
        @WebParam(name = "includedHeaders", targetNamespace = "http://www.acumatica.com/generic/")
        boolean includedHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnError,
        @WebParam(name = "breakOnIncorrectTarget", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnIncorrectTarget);

    /**
     * 
     * @param commands
     * @return
     *     returns com.prime.jax.SM201010ArrayOfContent
     */
    @WebMethod(operationName = "SM201010Submit", action = "http://www.acumatica.com/generic/SM201010/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM201010Submit", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010Submit")
    @ResponseWrapper(localName = "SM201010SubmitResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM201010SubmitResponse")
    public SM201010ArrayOfContent sm201010Submit(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands);

    /**
     * 
     */
    @WebMethod(operationName = "SM203520Clear", action = "http://www.acumatica.com/generic/SM203520/Clear")
    @RequestWrapper(localName = "SM203520Clear", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520Clear")
    @ResponseWrapper(localName = "SM203520ClearResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520ClearResponse")
    public void sm203520Clear();

    /**
     * 
     * @return
     *     returns com.prime.jax.ProcessResult
     */
    @WebMethod(operationName = "SM203520GetProcessStatus", action = "http://www.acumatica.com/generic/SM203520/GetProcessStatus")
    @WebResult(name = "GetProcessStatusResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM203520GetProcessStatus", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520GetProcessStatus")
    @ResponseWrapper(localName = "SM203520GetProcessStatusResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520GetProcessStatusResponse")
    public ProcessResult sm203520GetProcessStatus();

    /**
     * 
     * @return
     *     returns com.prime.jax.SM203520Content
     */
    @WebMethod(operationName = "SM203520GetSchema", action = "http://www.acumatica.com/generic/SM203520/GetSchema")
    @WebResult(name = "GetSchemaResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM203520GetSchema", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520GetSchema")
    @ResponseWrapper(localName = "SM203520GetSchemaResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520GetSchemaResponse")
    public SM203520Content sm203520GetSchema();

    /**
     * 
     * @param schema
     */
    @WebMethod(operationName = "SM203520SetSchema", action = "http://www.acumatica.com/generic/SM203520/SetSchema")
    @RequestWrapper(localName = "SM203520SetSchema", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520SetSchema")
    @ResponseWrapper(localName = "SM203520SetSchemaResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520SetSchemaResponse")
    public void sm203520SetSchema(
        @WebParam(name = "schema", targetNamespace = "http://www.acumatica.com/generic/")
        SM203520Content schema);

    /**
     * 
     * @param topCount
     * @param filters
     * @param includeHeaders
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.ArrayOfArrayOfString
     */
    @WebMethod(operationName = "SM203520Export", action = "http://www.acumatica.com/generic/SM203520/Export")
    @WebResult(name = "ExportResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM203520Export", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520Export")
    @ResponseWrapper(localName = "SM203520ExportResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520ExportResponse")
    public ArrayOfArrayOfString sm203520Export(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfFilter filters,
        @WebParam(name = "topCount", targetNamespace = "http://www.acumatica.com/generic/")
        int topCount,
        @WebParam(name = "includeHeaders", targetNamespace = "http://www.acumatica.com/generic/")
        boolean includeHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnError);

    /**
     * 
     * @param data
     * @param breakOnIncorrectTarget
     * @param includedHeaders
     * @param filters
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.SM203520ArrayOfImportResult
     */
    @WebMethod(operationName = "SM203520Import", action = "http://www.acumatica.com/generic/SM203520/Import")
    @WebResult(name = "ImportResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM203520Import", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520Import")
    @ResponseWrapper(localName = "SM203520ImportResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520ImportResponse")
    public SM203520ArrayOfImportResult sm203520Import(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfFilter filters,
        @WebParam(name = "data", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfArrayOfString data,
        @WebParam(name = "includedHeaders", targetNamespace = "http://www.acumatica.com/generic/")
        boolean includedHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnError,
        @WebParam(name = "breakOnIncorrectTarget", targetNamespace = "http://www.acumatica.com/generic/")
        boolean breakOnIncorrectTarget);

    /**
     * 
     * @param commands
     * @return
     *     returns com.prime.jax.SM203520ArrayOfContent
     */
    @WebMethod(operationName = "SM203520Submit", action = "http://www.acumatica.com/generic/SM203520/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://www.acumatica.com/generic/")
    @RequestWrapper(localName = "SM203520Submit", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520Submit")
    @ResponseWrapper(localName = "SM203520SubmitResponse", targetNamespace = "http://www.acumatica.com/generic/", className = "com.prime.jax.SM203520SubmitResponse")
    public SM203520ArrayOfContent sm203520Submit(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/generic/")
        ArrayOfCommand commands);

}
