//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.30 at 07:59:27 PM NZDT 
//


package com.prime.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElementTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ElementTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="String"/&gt;
 *     &lt;enumeration value="AsciiString"/&gt;
 *     &lt;enumeration value="StringSelector"/&gt;
 *     &lt;enumeration value="ExplicitSelector"/&gt;
 *     &lt;enumeration value="Number"/&gt;
 *     &lt;enumeration value="Option"/&gt;
 *     &lt;enumeration value="WideOption"/&gt;
 *     &lt;enumeration value="Calendar"/&gt;
 *     &lt;enumeration value="Action"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ElementTypes")
@XmlEnum
public enum ElementTypes {

    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("AsciiString")
    ASCII_STRING("AsciiString"),
    @XmlEnumValue("StringSelector")
    STRING_SELECTOR("StringSelector"),
    @XmlEnumValue("ExplicitSelector")
    EXPLICIT_SELECTOR("ExplicitSelector"),
    @XmlEnumValue("Number")
    NUMBER("Number"),
    @XmlEnumValue("Option")
    OPTION("Option"),
    @XmlEnumValue("WideOption")
    WIDE_OPTION("WideOption"),
    @XmlEnumValue("Calendar")
    CALENDAR("Calendar"),
    @XmlEnumValue("Action")
    ACTION("Action");
    private final String value;

    ElementTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ElementTypes fromValue(String v) {
        for (ElementTypes c: ElementTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
