//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.01 at 07:35:09 PM NZDT 
//


package com.prime.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.prime.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.prime.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetScenario }
     * 
     */
    public GetScenario createGetScenario() {
        return new GetScenario();
    }

    /**
     * Create an instance of {@link GetScenarioResponse }
     * 
     */
    public GetScenarioResponse createGetScenarioResponse() {
        return new GetScenarioResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCommand }
     * 
     */
    public ArrayOfCommand createArrayOfCommand() {
        return new ArrayOfCommand();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LoginResult }
     * 
     */
    public LoginResult createLoginResult() {
        return new LoginResult();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link SetBusinessDate }
     * 
     */
    public SetBusinessDate createSetBusinessDate() {
        return new SetBusinessDate();
    }

    /**
     * Create an instance of {@link SetBusinessDateResponse }
     * 
     */
    public SetBusinessDateResponse createSetBusinessDateResponse() {
        return new SetBusinessDateResponse();
    }

    /**
     * Create an instance of {@link SetLocaleName }
     * 
     */
    public SetLocaleName createSetLocaleName() {
        return new SetLocaleName();
    }

    /**
     * Create an instance of {@link SetLocaleNameResponse }
     * 
     */
    public SetLocaleNameResponse createSetLocaleNameResponse() {
        return new SetLocaleNameResponse();
    }

    /**
     * Create an instance of {@link SetSchemaMode }
     * 
     */
    public SetSchemaMode createSetSchemaMode() {
        return new SetSchemaMode();
    }

    /**
     * Create an instance of {@link SetSchemaModeResponse }
     * 
     */
    public SetSchemaModeResponse createSetSchemaModeResponse() {
        return new SetSchemaModeResponse();
    }

    /**
     * Create an instance of {@link SM201010Clear }
     * 
     */
    public SM201010Clear createSM201010Clear() {
        return new SM201010Clear();
    }

    /**
     * Create an instance of {@link SM201010ClearResponse }
     * 
     */
    public SM201010ClearResponse createSM201010ClearResponse() {
        return new SM201010ClearResponse();
    }

    /**
     * Create an instance of {@link SM201010GetProcessStatus }
     * 
     */
    public SM201010GetProcessStatus createSM201010GetProcessStatus() {
        return new SM201010GetProcessStatus();
    }

    /**
     * Create an instance of {@link SM201010GetProcessStatusResponse }
     * 
     */
    public SM201010GetProcessStatusResponse createSM201010GetProcessStatusResponse() {
        return new SM201010GetProcessStatusResponse();
    }

    /**
     * Create an instance of {@link ProcessResult }
     * 
     */
    public ProcessResult createProcessResult() {
        return new ProcessResult();
    }

    /**
     * Create an instance of {@link SM201010GetSchema }
     * 
     */
    public SM201010GetSchema createSM201010GetSchema() {
        return new SM201010GetSchema();
    }

    /**
     * Create an instance of {@link SM201010GetSchemaResponse }
     * 
     */
    public SM201010GetSchemaResponse createSM201010GetSchemaResponse() {
        return new SM201010GetSchemaResponse();
    }

    /**
     * Create an instance of {@link SM201010Content }
     * 
     */
    public SM201010Content createSM201010Content() {
        return new SM201010Content();
    }

    /**
     * Create an instance of {@link SM201010SetSchema }
     * 
     */
    public SM201010SetSchema createSM201010SetSchema() {
        return new SM201010SetSchema();
    }

    /**
     * Create an instance of {@link SM201010SetSchemaResponse }
     * 
     */
    public SM201010SetSchemaResponse createSM201010SetSchemaResponse() {
        return new SM201010SetSchemaResponse();
    }

    /**
     * Create an instance of {@link SM201010Export }
     * 
     */
    public SM201010Export createSM201010Export() {
        return new SM201010Export();
    }

    /**
     * Create an instance of {@link ArrayOfFilter }
     * 
     */
    public ArrayOfFilter createArrayOfFilter() {
        return new ArrayOfFilter();
    }

    /**
     * Create an instance of {@link SM201010ExportResponse }
     * 
     */
    public SM201010ExportResponse createSM201010ExportResponse() {
        return new SM201010ExportResponse();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfString }
     * 
     */
    public ArrayOfArrayOfString createArrayOfArrayOfString() {
        return new ArrayOfArrayOfString();
    }

    /**
     * Create an instance of {@link SM201010Import }
     * 
     */
    public SM201010Import createSM201010Import() {
        return new SM201010Import();
    }

    /**
     * Create an instance of {@link SM201010ImportResponse }
     * 
     */
    public SM201010ImportResponse createSM201010ImportResponse() {
        return new SM201010ImportResponse();
    }

    /**
     * Create an instance of {@link SM201010ArrayOfImportResult }
     * 
     */
    public SM201010ArrayOfImportResult createSM201010ArrayOfImportResult() {
        return new SM201010ArrayOfImportResult();
    }

    /**
     * Create an instance of {@link SM201010Submit }
     * 
     */
    public SM201010Submit createSM201010Submit() {
        return new SM201010Submit();
    }

    /**
     * Create an instance of {@link SM201010SubmitResponse }
     * 
     */
    public SM201010SubmitResponse createSM201010SubmitResponse() {
        return new SM201010SubmitResponse();
    }

    /**
     * Create an instance of {@link SM201010ArrayOfContent }
     * 
     */
    public SM201010ArrayOfContent createSM201010ArrayOfContent() {
        return new SM201010ArrayOfContent();
    }

    /**
     * Create an instance of {@link SM203520Clear }
     * 
     */
    public SM203520Clear createSM203520Clear() {
        return new SM203520Clear();
    }

    /**
     * Create an instance of {@link SM203520ClearResponse }
     * 
     */
    public SM203520ClearResponse createSM203520ClearResponse() {
        return new SM203520ClearResponse();
    }

    /**
     * Create an instance of {@link SM203520GetProcessStatus }
     * 
     */
    public SM203520GetProcessStatus createSM203520GetProcessStatus() {
        return new SM203520GetProcessStatus();
    }

    /**
     * Create an instance of {@link SM203520GetProcessStatusResponse }
     * 
     */
    public SM203520GetProcessStatusResponse createSM203520GetProcessStatusResponse() {
        return new SM203520GetProcessStatusResponse();
    }

    /**
     * Create an instance of {@link SM203520GetSchema }
     * 
     */
    public SM203520GetSchema createSM203520GetSchema() {
        return new SM203520GetSchema();
    }

    /**
     * Create an instance of {@link SM203520GetSchemaResponse }
     * 
     */
    public SM203520GetSchemaResponse createSM203520GetSchemaResponse() {
        return new SM203520GetSchemaResponse();
    }

    /**
     * Create an instance of {@link SM203520Content }
     * 
     */
    public SM203520Content createSM203520Content() {
        return new SM203520Content();
    }

    /**
     * Create an instance of {@link SM203520SetSchema }
     * 
     */
    public SM203520SetSchema createSM203520SetSchema() {
        return new SM203520SetSchema();
    }

    /**
     * Create an instance of {@link SM203520SetSchemaResponse }
     * 
     */
    public SM203520SetSchemaResponse createSM203520SetSchemaResponse() {
        return new SM203520SetSchemaResponse();
    }

    /**
     * Create an instance of {@link SM203520Export }
     * 
     */
    public SM203520Export createSM203520Export() {
        return new SM203520Export();
    }

    /**
     * Create an instance of {@link SM203520ExportResponse }
     * 
     */
    public SM203520ExportResponse createSM203520ExportResponse() {
        return new SM203520ExportResponse();
    }

    /**
     * Create an instance of {@link SM203520Import }
     * 
     */
    public SM203520Import createSM203520Import() {
        return new SM203520Import();
    }

    /**
     * Create an instance of {@link SM203520ImportResponse }
     * 
     */
    public SM203520ImportResponse createSM203520ImportResponse() {
        return new SM203520ImportResponse();
    }

    /**
     * Create an instance of {@link SM203520ArrayOfImportResult }
     * 
     */
    public SM203520ArrayOfImportResult createSM203520ArrayOfImportResult() {
        return new SM203520ArrayOfImportResult();
    }

    /**
     * Create an instance of {@link SM203520Submit }
     * 
     */
    public SM203520Submit createSM203520Submit() {
        return new SM203520Submit();
    }

    /**
     * Create an instance of {@link SM203520SubmitResponse }
     * 
     */
    public SM203520SubmitResponse createSM203520SubmitResponse() {
        return new SM203520SubmitResponse();
    }

    /**
     * Create an instance of {@link SM203520ArrayOfContent }
     * 
     */
    public SM203520ArrayOfContent createSM203520ArrayOfContent() {
        return new SM203520ArrayOfContent();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link ElementDescriptor }
     * 
     */
    public ElementDescriptor createElementDescriptor() {
        return new ElementDescriptor();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link EveryValue }
     * 
     */
    public EveryValue createEveryValue() {
        return new EveryValue();
    }

    /**
     * Create an instance of {@link Key }
     * 
     */
    public Key createKey() {
        return new Key();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link RowNumber }
     * 
     */
    public RowNumber createRowNumber() {
        return new RowNumber();
    }

    /**
     * Create an instance of {@link NewRow }
     * 
     */
    public NewRow createNewRow() {
        return new NewRow();
    }

    /**
     * Create an instance of {@link DeleteRow }
     * 
     */
    public DeleteRow createDeleteRow() {
        return new DeleteRow();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link SM201010Actions }
     * 
     */
    public SM201010Actions createSM201010Actions() {
        return new SM201010Actions();
    }

    /**
     * Create an instance of {@link SM201010UserInformation }
     * 
     */
    public SM201010UserInformation createSM201010UserInformation() {
        return new SM201010UserInformation();
    }

    /**
     * Create an instance of {@link SM201010UserInformationServiceCommands }
     * 
     */
    public SM201010UserInformationServiceCommands createSM201010UserInformationServiceCommands() {
        return new SM201010UserInformationServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010Statistics }
     * 
     */
    public SM201010Statistics createSM201010Statistics() {
        return new SM201010Statistics();
    }

    /**
     * Create an instance of {@link SM201010StatisticsServiceCommands }
     * 
     */
    public SM201010StatisticsServiceCommands createSM201010StatisticsServiceCommands() {
        return new SM201010StatisticsServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010PersonalSettings }
     * 
     */
    public SM201010PersonalSettings createSM201010PersonalSettings() {
        return new SM201010PersonalSettings();
    }

    /**
     * Create an instance of {@link SM201010PersonalSettingsServiceCommands }
     * 
     */
    public SM201010PersonalSettingsServiceCommands createSM201010PersonalSettingsServiceCommands() {
        return new SM201010PersonalSettingsServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010IPFilterAllowedIPAddressRanges }
     * 
     */
    public SM201010IPFilterAllowedIPAddressRanges createSM201010IPFilterAllowedIPAddressRanges() {
        return new SM201010IPFilterAllowedIPAddressRanges();
    }

    /**
     * Create an instance of {@link SM201010IPFilterAllowedIPAddressRangesServiceCommands }
     * 
     */
    public SM201010IPFilterAllowedIPAddressRangesServiceCommands createSM201010IPFilterAllowedIPAddressRangesServiceCommands() {
        return new SM201010IPFilterAllowedIPAddressRangesServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010ExternalIdentities }
     * 
     */
    public SM201010ExternalIdentities createSM201010ExternalIdentities() {
        return new SM201010ExternalIdentities();
    }

    /**
     * Create an instance of {@link SM201010ExternalIdentitiesServiceCommands }
     * 
     */
    public SM201010ExternalIdentitiesServiceCommands createSM201010ExternalIdentitiesServiceCommands() {
        return new SM201010ExternalIdentitiesServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010Roles }
     * 
     */
    public SM201010Roles createSM201010Roles() {
        return new SM201010Roles();
    }

    /**
     * Create an instance of {@link SM201010RolesServiceCommands }
     * 
     */
    public SM201010RolesServiceCommands createSM201010RolesServiceCommands() {
        return new SM201010RolesServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010ActiveDirectoryUserActiveDirectoryUser }
     * 
     */
    public SM201010ActiveDirectoryUserActiveDirectoryUser createSM201010ActiveDirectoryUserActiveDirectoryUser() {
        return new SM201010ActiveDirectoryUserActiveDirectoryUser();
    }

    /**
     * Create an instance of {@link SM201010ActiveDirectoryUserActiveDirectoryUserServiceCommands }
     * 
     */
    public SM201010ActiveDirectoryUserActiveDirectoryUserServiceCommands createSM201010ActiveDirectoryUserActiveDirectoryUserServiceCommands() {
        return new SM201010ActiveDirectoryUserActiveDirectoryUserServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010LicenseTypes }
     * 
     */
    public SM201010LicenseTypes createSM201010LicenseTypes() {
        return new SM201010LicenseTypes();
    }

    /**
     * Create an instance of {@link SM201010LicenseTypesServiceCommands }
     * 
     */
    public SM201010LicenseTypesServiceCommands createSM201010LicenseTypesServiceCommands() {
        return new SM201010LicenseTypesServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010RolesRoleName }
     * 
     */
    public SM201010RolesRoleName createSM201010RolesRoleName() {
        return new SM201010RolesRoleName();
    }

    /**
     * Create an instance of {@link SM201010RolesRoleNameServiceCommands }
     * 
     */
    public SM201010RolesRoleNameServiceCommands createSM201010RolesRoleNameServiceCommands() {
        return new SM201010RolesRoleNameServiceCommands();
    }

    /**
     * Create an instance of {@link SM201010PrimaryKey }
     * 
     */
    public SM201010PrimaryKey createSM201010PrimaryKey() {
        return new SM201010PrimaryKey();
    }

    /**
     * Create an instance of {@link SM201010ImportResult }
     * 
     */
    public SM201010ImportResult createSM201010ImportResult() {
        return new SM201010ImportResult();
    }

    /**
     * Create an instance of {@link SM203520Actions }
     * 
     */
    public SM203520Actions createSM203520Actions() {
        return new SM203520Actions();
    }

    /**
     * Create an instance of {@link SM203520CompanySummary }
     * 
     */
    public SM203520CompanySummary createSM203520CompanySummary() {
        return new SM203520CompanySummary();
    }

    /**
     * Create an instance of {@link SM203520CompanySummaryServiceCommands }
     * 
     */
    public SM203520CompanySummaryServiceCommands createSM203520CompanySummaryServiceCommands() {
        return new SM203520CompanySummaryServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520Snapshots }
     * 
     */
    public SM203520Snapshots createSM203520Snapshots() {
        return new SM203520Snapshots();
    }

    /**
     * Create an instance of {@link SM203520SnapshotsServiceCommands }
     * 
     */
    public SM203520SnapshotsServiceCommands createSM203520SnapshotsServiceCommands() {
        return new SM203520SnapshotsServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520SnapshotRestorationHistory }
     * 
     */
    public SM203520SnapshotRestorationHistory createSM203520SnapshotRestorationHistory() {
        return new SM203520SnapshotRestorationHistory();
    }

    /**
     * Create an instance of {@link SM203520SnapshotRestorationHistoryServiceCommands }
     * 
     */
    public SM203520SnapshotRestorationHistoryServiceCommands createSM203520SnapshotRestorationHistoryServiceCommands() {
        return new SM203520SnapshotRestorationHistoryServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520Users }
     * 
     */
    public SM203520Users createSM203520Users() {
        return new SM203520Users();
    }

    /**
     * Create an instance of {@link SM203520UsersServiceCommands }
     * 
     */
    public SM203520UsersServiceCommands createSM203520UsersServiceCommands() {
        return new SM203520UsersServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520CopyCompany }
     * 
     */
    public SM203520CopyCompany createSM203520CopyCompany() {
        return new SM203520CopyCompany();
    }

    /**
     * Create an instance of {@link SM203520CopyCompanyServiceCommands }
     * 
     */
    public SM203520CopyCompanyServiceCommands createSM203520CopyCompanyServiceCommands() {
        return new SM203520CopyCompanyServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520CreateSnapshot }
     * 
     */
    public SM203520CreateSnapshot createSM203520CreateSnapshot() {
        return new SM203520CreateSnapshot();
    }

    /**
     * Create an instance of {@link SM203520CreateSnapshotServiceCommands }
     * 
     */
    public SM203520CreateSnapshotServiceCommands createSM203520CreateSnapshotServiceCommands() {
        return new SM203520CreateSnapshotServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520ResetData }
     * 
     */
    public SM203520ResetData createSM203520ResetData() {
        return new SM203520ResetData();
    }

    /**
     * Create an instance of {@link SM203520ResetDataServiceCommands }
     * 
     */
    public SM203520ResetDataServiceCommands createSM203520ResetDataServiceCommands() {
        return new SM203520ResetDataServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520RestoreSnapshot }
     * 
     */
    public SM203520RestoreSnapshot createSM203520RestoreSnapshot() {
        return new SM203520RestoreSnapshot();
    }

    /**
     * Create an instance of {@link SM203520RestoreSnapshotServiceCommands }
     * 
     */
    public SM203520RestoreSnapshotServiceCommands createSM203520RestoreSnapshotServiceCommands() {
        return new SM203520RestoreSnapshotServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520RestoreSnapshotOnProduction }
     * 
     */
    public SM203520RestoreSnapshotOnProduction createSM203520RestoreSnapshotOnProduction() {
        return new SM203520RestoreSnapshotOnProduction();
    }

    /**
     * Create an instance of {@link SM203520RestoreSnapshotOnProductionServiceCommands }
     * 
     */
    public SM203520RestoreSnapshotOnProductionServiceCommands createSM203520RestoreSnapshotOnProductionServiceCommands() {
        return new SM203520RestoreSnapshotOnProductionServiceCommands();
    }

    /**
     * Create an instance of {@link SM203520PrimaryKey }
     * 
     */
    public SM203520PrimaryKey createSM203520PrimaryKey() {
        return new SM203520PrimaryKey();
    }

    /**
     * Create an instance of {@link SM203520ImportResult }
     * 
     */
    public SM203520ImportResult createSM203520ImportResult() {
        return new SM203520ImportResult();
    }

}
