//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.30 at 07:59:27 PM NZDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.acumatica.com/generic/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.prime.wsdl;
