
package com.prime.jax.sm507000;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScreenSoap", targetNamespace = "http://www.acumatica.com/typed/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScreenSoap {


    /**
     * 
     */
    @WebMethod(operationName = "Clear", action = "http://www.acumatica.com/typed/Clear")
    @RequestWrapper(localName = "Clear", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Clear")
    @ResponseWrapper(localName = "ClearResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.ClearResponse")
    public void clear();

    /**
     * 
     * @return
     *     returns com.prime.jax.sm507000.ProcessResult
     */
    @WebMethod(operationName = "GetProcessStatus", action = "http://www.acumatica.com/typed/GetProcessStatus")
    @WebResult(name = "GetProcessStatusResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "GetProcessStatus", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetProcessStatus")
    @ResponseWrapper(localName = "GetProcessStatusResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetProcessStatusResponse")
    public ProcessResult getProcessStatus();

    /**
     * 
     * @param scenario
     * @return
     *     returns com.prime.jax.sm507000.ArrayOfCommand
     */
    @WebMethod(operationName = "GetScenario", action = "http://www.acumatica.com/typed/GetScenario")
    @WebResult(name = "GetScenarioResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "GetScenario", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetScenario")
    @ResponseWrapper(localName = "GetScenarioResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetScenarioResponse")
    public ArrayOfCommand getScenario(
        @WebParam(name = "scenario", targetNamespace = "http://www.acumatica.com/typed/")
        String scenario);

    /**
     * 
     * @return
     *     returns com.prime.jax.sm507000.Content
     */
    @WebMethod(operationName = "GetSchema", action = "http://www.acumatica.com/typed/GetSchema")
    @WebResult(name = "GetSchemaResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "GetSchema", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetSchema")
    @ResponseWrapper(localName = "GetSchemaResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.GetSchemaResponse")
    public Content getSchema();

    /**
     * 
     * @param schema
     */
    @WebMethod(operationName = "SetSchema", action = "http://www.acumatica.com/typed/SetSchema")
    @RequestWrapper(localName = "SetSchema", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetSchema")
    @ResponseWrapper(localName = "SetSchemaResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetSchemaResponse")
    public void setSchema(
        @WebParam(name = "schema", targetNamespace = "http://www.acumatica.com/typed/")
        Content schema);

    /**
     * 
     * @param topCount
     * @param filters
     * @param includeHeaders
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.sm507000.ArrayOfArrayOfString
     */
    @WebMethod(operationName = "Export", action = "http://www.acumatica.com/typed/Export")
    @WebResult(name = "ExportResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "Export", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Export")
    @ResponseWrapper(localName = "ExportResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.ExportResponse")
    public ArrayOfArrayOfString SM507000Export(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfFilter filters,
        @WebParam(name = "topCount", targetNamespace = "http://www.acumatica.com/typed/")
        int topCount,
        @WebParam(name = "includeHeaders", targetNamespace = "http://www.acumatica.com/typed/")
        boolean includeHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/typed/")
        boolean breakOnError);

    /**
     * 
     * @param data
     * @param breakOnIncorrectTarget
     * @param includedHeaders
     * @param filters
     * @param breakOnError
     * @param commands
     * @return
     *     returns com.prime.jax.sm507000.ArrayOfImportResult
     */
    @WebMethod(operationName = "Import", action = "http://www.acumatica.com/typed/Import")
    @WebResult(name = "ImportResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "Import", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Import")
    @ResponseWrapper(localName = "ImportResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.ImportResponse")
    public ArrayOfImportResult SM507000Import(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfCommand commands,
        @WebParam(name = "filters", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfFilter filters,
        @WebParam(name = "data", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfArrayOfString data,
        @WebParam(name = "includedHeaders", targetNamespace = "http://www.acumatica.com/typed/")
        boolean includedHeaders,
        @WebParam(name = "breakOnError", targetNamespace = "http://www.acumatica.com/typed/")
        boolean breakOnError,
        @WebParam(name = "breakOnIncorrectTarget", targetNamespace = "http://www.acumatica.com/typed/")
        boolean breakOnIncorrectTarget);

    /**
     * 
     * @param commands
     * @return
     *     returns com.prime.jax.sm507000.ArrayOfContent
     */
    @WebMethod(operationName = "Submit", action = "http://www.acumatica.com/typed/Submit")
    @WebResult(name = "SubmitResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "Submit", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Submit")
    @ResponseWrapper(localName = "SubmitResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SubmitResponse")
    public ArrayOfContent submit(
        @WebParam(name = "commands", targetNamespace = "http://www.acumatica.com/typed/")
        ArrayOfCommand commands);

    /**
     * 
     * @param password
     * @param name
     * @return
     *     returns com.prime.jax.sm507000.LoginResult
     */
    @WebMethod(operationName = "Login", action = "http://www.acumatica.com/typed/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://www.acumatica.com/typed/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.LoginResponse")
    public LoginResult login(
        @WebParam(name = "name", targetNamespace = "http://www.acumatica.com/typed/")
        String name,
        @WebParam(name = "password", targetNamespace = "http://www.acumatica.com/typed/")
        String password);

    /**
     * 
     */
    @WebMethod(operationName = "Logout", action = "http://www.acumatica.com/typed/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.LogoutResponse")
    public void logout();

    /**
     * 
     * @param date
     */
    @WebMethod(operationName = "SetBusinessDate", action = "http://www.acumatica.com/typed/SetBusinessDate")
    @RequestWrapper(localName = "SetBusinessDate", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetBusinessDate")
    @ResponseWrapper(localName = "SetBusinessDateResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetBusinessDateResponse")
    public void setBusinessDate(
        @WebParam(name = "date", targetNamespace = "http://www.acumatica.com/typed/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param localeName
     */
    @WebMethod(operationName = "SetLocaleName", action = "http://www.acumatica.com/typed/SetLocaleName")
    @RequestWrapper(localName = "SetLocaleName", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetLocaleName")
    @ResponseWrapper(localName = "SetLocaleNameResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetLocaleNameResponse")
    public void setLocaleName(
        @WebParam(name = "localeName", targetNamespace = "http://www.acumatica.com/typed/")
        String localeName);

    /**
     * 
     * @param mode
     */
    @WebMethod(operationName = "SetSchemaMode", action = "http://www.acumatica.com/typed/SetSchemaMode")
    @RequestWrapper(localName = "SetSchemaMode", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetSchemaMode")
    @ResponseWrapper(localName = "SetSchemaModeResponse", targetNamespace = "http://www.acumatica.com/typed/", className = "com.prime.jax.sm507000.SetSchemaModeResponse")
    public void setSchemaMode(
        @WebParam(name = "mode", targetNamespace = "http://www.acumatica.com/typed/")
        SchemaMode mode);

}
